name: CI/CD to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포 클론
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Node.js 세팅
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. .env 파일 생성
      - name: Create .env from Secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 5. 빌드
      - name: Build React App
        run: npm run build

      # 6. AWS CLI 세팅
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 7. S3에 업로드 (dist 디렉토리 사용)
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://core-syncc.com --delete

      # 8. CloudFront 캐시 무효화
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
